### ISSUE TITLE
iframe src attribute with ampersands in the URL

### ISSUE THREAD

**Issue by stevecomrie** [lincanbin/White-HTML-Filter#1]
I was running into an issue with iframe sources that had an ampersand in the URL, like:

https://www.youtube.com/embed/lBOwxXxesBo?rel=0&showinfo=0

Basically, using a config that allowed iframes (and allowed the src attribute), URLs without an ampersand would make it thought the filter no problem, but URLs that *had* an ampersand would get cleared.

So next I tried to create a URL regex filter based on your documentation, but that still wasn't working, so I tried the most basic filtering function I could:

`$iframeUrlFilter = function($url) { return $url; };`

But this was *still* failing. URLs without and ampersand worked fine, URLs with an ampersand got cleaned to nothing.

If I completely commented out line 200 in WhiteHTMLFilter.php

`$domAttr->value = $attributesFilterMap[$attrName]($domAttr->value);`

Then everything worked properly, but obviously, that was not ideal for a variety of reasons, but it at least proved to me where the data was going missing.

Surprisingly, even if I replaced line 200 with the following, the system *STILL* filtered our src URLs containing an ampersand:

`$domAttr->value = $domAttr->value;`

Which was so far beyond a head scratcher that I was at a loss for words.

After much struggling, I finally landed on replacing my filter with this:

`$iframeUrlFilter = function($url) { return str_replace( '&', '&amp;', $url ); };`

For some reason, that filter works properly and allows iframe src's that contain an ampersand.

Anyway, I'm not 100% sure WHY the code for the filter forces me to do that, I was scratching my head for the better part of an hour trying to figure it out, but I thought you might want to know incase you have a better idea or if you wanted to investigate further.

**Comment by lincanbin** [comment]
https://stackoverflow.com/questions/1685277/warning-domdocumentloadhtml-htmlparseentityref-expecting-in-entity?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

This seems to be a long-standing bug in PHP.

**Comment by lincanbin** [comment]
https://stackoverflow.com/questions/9150931/domattrs-value-attribute-is-confusing

**Comment by lincanbin** [comment]
Seemingly separate ampersands are illegal characters in standard HTML attribute values.

**Comment by lincanbin** [comment]
https://github.com/lincanbin/White-HTML-Filter/releases/tag/v1.3

try this.
